config/routes.rb
VisibleCloset::Application.routes.draw do

  resources :orders
  resources :products
  resources :storage_charge_processing_records
  resources :storage_payment_processing_records

  match "/register" => "pages#register_block"
  match "/register_interest" => "pages#register_interest"
  match "boxes/receive_box" => "boxes#receive_box"
  match "boxes/inventory_box" => "boxes#inventory_box"
  match "boxes/delete_stored_item" => "boxes#delete_stored_item"
  match "boxes/inventory_boxes" => "boxes#inventory_boxes"
  match "boxes/clear_box" => "boxes#clear_box"
  match "boxes/add_tags" => "boxes#add_tags"
  match "boxes/add_tag" => "boxes#add_tag"
  match "boxes/user_add_tag" => "boxes#user_add_tag"
  match "boxes/delete_tag" => "boxes#delete_tag"
  match "boxes/user_delete_tag" => "boxes#user_delete_tag"
  match "boxes/:id/request_box_return" => "boxes#request_box_return"
  match "boxes/:id/cancel_box_return_request" => "boxes#cancel_box_return_request"
  match "boxes/finish_inventorying_box" => "boxes#finish_inventorying"
  get "stored_items/autocomplete_stored_item_tags"
  match "stored_items/:id" => "stored_items#view"
  
  match "payment_profiles/:id/set_default" => "payment_profiles#set_default"
  match "addresses/:id/set_default_shipping" => "addresses#set_default_shipping"
  match "m" => "pages#marketing_hit"
  get "addresses/new_default_shipping_address"
  post "addresses/set_default_shipping_address"
  match "addresses/:id/update_default_shipping_address" => "addresses#set_default_shipping_address"
  match "addresses/:id/override_fedex" => "addresses#override_fedex"
  get "addresses/confirm_new_default_shipping_address"
  get "addresses/confirm_address"
  match "addresses/:id/confirm_address" => "addresses#confirm_address"
  get "payment_profiles/new_default_payment_profile"
  post "payment_profiles/create_default_payment_profile"
  post "addresses/admin_fedex_override"
  match "account/set_checkout_shipping_address" => "addresses#set_checkout_shipping_address"
  match "account/new_checkout_shipping_address" => "addresses#new_checkout_shipping_address"
  match "/account/update_new_checkout_shipping_address/:id" => "addresses#update_new_checkout_shipping_address"
  
  match "stored_items/:id/request_donation" => "stored_items#request_charitable_donation"
  match "stored_items/:id/cancel_donation_request" => "stored_items#cancel_donation_request"
  match "stored_items/:id/request_mailing" => "stored_items#request_mailing"
  match "stored_items/:id/cancel_mailing_request" => "stored_items#cancel_mailing_request"
  match "stored_items/:id/cancel_retrieval_request" => "stored_items#cancel_retrieval_request"
  match "stored_items/:id/request_retrieval" => "stored_items#request_retrieval"
  match "/stored_items" => "stored_items#index"
  match "/furniture_items" => "furniture_items#index"
  match "/furniture_items/:id" => "furniture_items#view"
  match "furniture_items/:id/save_description" => "furniture_items#save_description"
  
  resources :boxes
  resources :addresses
  resources :payment_profiles
  resources :rental_agreement_versions
  
  match "orders/:id/process" => "orders#process_order"
  match "orders/:id/process_item_mailing_order_lines" => "orders#process_item_mailing_order_lines"
  match "orders/:id/ship_item_mailing_order_lines" => "orders#ship_item_mailing_order_lines"
  match "orders/:id/price_item_mailing_order_lines" => "orders#price_item_mailing_order_lines"
  match "orders/:id/add_shipping_charge" => "orders#add_shipping_charge"
  match "orders/:id/ship_order_lines" => "orders#ship_order_lines"
  match "order_lines/:id/cancel" => "orders#cancel_order_line"
  match "boxes/:box_id/stored_items" => "stored_items#index"
  match "boxes/:id/request_inventory" => "boxes#request_inventory"
  match "box/:id/get_label" => "boxes#get_label"
  match "boxes/:id/email_shipping_label" => "boxes#email_shipping_label"
  match "shipment/:id/get_label" => "shipments#get_label"
  match "stored_item_tags/:id/delete" => "stored_item_tags#delete"
  match "stored_item_tags/add_tag" => "stored_item_tags#add_tag"

  devise_for :users, :path_names => { :sign_up => "register" }, \
    :controllers => { :registrations => "registrations", :confirmations => "confirmations", :sessions => "sessions", :passwords => "passwords" }
  match '/user' => "account#index", :as => :user_root

  get "home/index"
  match "access_denied" => "home#access_denied"
  match "how_it_works" => "pages#how_it_works"
  match "restrictions" => "pages#restrictions"
  match "contact" => "pages#contact"
  match "pages/contact_post" => "pages#contact_post"
  match "pages/support_post" => "pages#support_post"
  match "packing_tips" => "pages#packing_tips"
  match "right_for_me" => "pages#right_for_me"
  match "faq" => "pages#faq"
  match "legal" => "pages#legal"
  match "pricing" => "pages#pricing"
  match "privacy" => "pages#privacy"
  match "support" => "pages#support"
  match "member_agreement_ajax" => "rental_agreement_versions#latest_agreement_ajax"
  match "member_agreement" => "rental_agreement_versions#latest_agreement"
  get "pages/fedex_unavailable"
  get "pages/request_confirmation"
  match "pages/test_validate_address" => "pages#test_validate_address"
  
  match "admin/home" => "admin#process_orders"
  get "admin/shipping"
  get "admin/inventory_boxes"
  get "admin/process_orders"
  get "admin/monthly_charges"
  post "admin/send_boxes_user_search"
  post "admin/generate_charges"
  get "admin/users"
  match "admin/user/:id/addresses" => "admin#user_addresses"
  match "admin/user/:id/switch_test_user_status" => "admin#switch_test_user_status"
  match "admin/user/:id" => "admin#user"
  match "admin/user/:id/clear_test_data" => "admin#clear_user_data"
  match "admin/user/:id/destroy" => "admin#destroy_user"
  match "admin/user/:id/orders" => "admin#user_orders"
  match "admin/user/:user_id/order/:order_id/destroy" => "admin#delete_user_order"
  match "admin/users/:id/create_customer_boxes" => "boxes#create_customer_boxes"
  match "admin/users/:id/add_customer_boxes" => "boxes#add_customer_boxes"
  match "admin/users/:id/furniture" => "furniture_items#admin_index"
  match "admin/users/:id/add_furniture_item" => "furniture_items#admin_add"
  match "admin/users/:id/create_furniture_item" => "furniture_items#admin_create"
  match "admin/shipment/:id/destroy" => "admin#delete_shipment"
  match "admin/user/:id/shipments" => "admin#user_shipments"
  match "admin/user/:id/shipment/:shipment_id/destroy" => "admin#delete_user_shipment"
  match "admin/shipment/:id" => "admin#shipment"
  match "admin/shipment/:id/resend_label" => "admin#resend_label"
  match "admin/shipment/:id/refresh_fedex_events" => "admin#refresh_shipment_events"
  match "admin/shipment/:id/set_charge" => "admin#set_shipment_charge"
  match "admin/user/:user_id/new_address" => "addresses#admin_new_address"
  match "admin/user/:user_id/create_address/:id" => "addresses#admin_create_address"
  match "admin/user/:user_id/create_address" => "addresses#admin_create_address"
  match "admin/user/:user_id/confirm_address" => "addresses#admin_confirm_address"
  match "admin/double_post"
  match "admin/user/:id/boxes" => "admin#user_boxes"
  match "admin/user/:user_id/boxes/:box_id/destroy" => "admin#delete_user_box"
  match "admin/user/:user_id/boxes/:box_id" => "admin#user_box"
  match "admin/user/:user_id/boxes/:box_id/manual_return" => "admin#manual_box_return"
  match "admin/user/:user_id/orders/:order_id" => "admin#user_order"
  match "admin/user/:id/billing" => "admin#user_billing"
  match "admin/invoices/:id" => "orders#show_invoice"
  match "admin/user/:user_id/subscriptions/:subscription_id" => "admin#user_subscription"
  match "admin/charges/:id/delete" => "admin#delete_charge"
  match "admin/credits/:id/delete" => "admin#delete_credit"
  match "admin/generate_payments" => "admin#generate_payments"
  match "admin/user_account_balances" => "admin#user_account_balances"
  match "admin/impersonate_user/:id" => "admin#impersonate_user"
  match "admin/stop_impersonating" => "admin#stop_impersonating"
  match "admin/users/:id/add_charge" => "admin#add_user_charge"
  match "admin/billing/charges/:id/destroy" => "admin#destroy_billing_charge"
  match "admin/users/:id/add_credit" => "admin#add_user_credit"
  match "admin/billing/credits/:id/destroy" => "admin#destroy_billing_credit"
  
  resources :offers
  match "offers/:id/activate" => "offers#activate"
  match "offers/:id/add_coupons" => "offers#add_coupons"
  match "coupons/:id/delete" => "offers#destroy_coupon"
  match "offers/:id/coupons" => "offers#coupons"
  match "view_offers" => "offers#user_offers_coupons"
  match "apply_offer_code" => "offers#apply_offer_code"
  match "admin/:id/dissociate_offer_from_user" => "offers#dissociate_offer_from_user"
  match "user_offers/:id/apply_boxes" => "offers#user_offer_apply_boxes"
  match "user_coupons/:id/apply_boxes" => "offers#user_coupon_apply_boxes"
  match "user_offers/:id/assign_to_boxes" => "offers#assign_boxes_to_offer"
  match "user_coupons/:id/assign_to_boxes" => "offers#assign_boxes_to_coupon"

  match "admin/furniture_items/:id/photos" => "furniture_items#admin_manage_photos"
  match "admin/furniture_items/:id/create_photo" => "furniture_items#admin_create_photo"
  match "admin/furniture_items/:id/edit" => "furniture_items#admin_edit"
  match "admin/furniture_items/:id/save" => "furniture_items#admin_save"
  match "admin/furniture_items/:id/destroy" => "furniture_items#admin_destroy_furniture_item"
  match "admin/furniture_items/:furniture_item_id/photos/:photo_id/destroy" => "furniture_items#admin_destroy_photo"
  match "admin/furniture_items/:id/publish" => "furniture_items#admin_publish_furniture_item"
  match "admin/furniture_items/:id/unpublish" => "furniture_items#admin_unpublish_furniture_item"
  match "admin/furniture_items/:furniture_item_id/photos/:photo_id/save" => "furniture_items#save_photo"
  match "admin/furniture_items/:id" => "furniture_items#admin_view"

app/helpers/boxes_helper.rb
module BoxesHelper
end

app/views/boxes/_photo.html.erb
<div class="imgteaser"> 
<a href="delete_stored_item?id=<%= @stored_item.id.to_s %>&amp;box_id=<%= @stored_item.box_id %>">
<%= image_tag(@stored_item.photo.url(:thumb)) %>
	<!--<span class="more">&raquo; Learn More</span> -->
	<span class="desc"> 
		Delete
	</span> 
</a>
</div>

app/views/boxes/_plupload.js.erb
<% session_key_name = Rails.application.config.session_options[:key] %>
jQuery(document).ready(function() {
  $("#uploader").pluploadQueue({
    runtimes: 'html5,flash,silverlight',
    url: '/boxes/create_stored_item',
    max_file_size: '10mb',
    multiple_queues: true,
    flash_swf_url: "/javascripts/plupload/plupload.flash.swf",  
    silverlight_xap_url: "/javascripts/plupload/plupload.silverlight.xap",
    multipart: true,
    multipart_params: {
      'box_id': '<%= @box.id %>',
      '_http_accept': 'application/javascript',
      'authenticity_token' : '<%= form_authenticity_token %>',
      '<%= session_key_name %>' : encodeURIComponent('<%= u cookies[session_key_name] %>')
    },
    filters: [
      {title: "Images", extensions: "jpg,jpeg,png,gif"}
    ],
    init: {
      FileUploaded: function(up, file, info) {
        eval(info["response"]);
      }
    }
  });
});

app/views/boxes/_stored_item_tag.html.erb
<div id="stored_item_tag_<%= @stored_item_tag.id %>" class="stored_item_tag"><%= @stored_item_tag.tag %>   <%= link_to("(delete)", "/boxes/delete_tag?id=" + @stored_item_tag.id.to_s, :method => :delete, :remote => true) %>
</div>

app/views/boxes/_user_stored_item_tags.html.erb
<% @stored_item.stored_item_tags.each_with_index do |tag, index| %>
	<% if index % 7 != 0 %>
	| 
	<% end %>
	<%= tag.tag %> <%= link_to("(X)", "/boxes/user_delete_tag?id=" + tag.id.to_s, :alt => "delete this tag", :title => "delete this tag", :method => :delete, :remote => true) %>
	<% if (index + 1) % 7 == 0 && (index + 1) != @stored_item.stored_item_tags.size %>
		<br>
	<% end %>	
<% end %>

app/views/boxes/cancel_box_return_request.js.erb
// Change the clicked box image
var box_img = document.getElementById('box_img_<%= @box.id %>');
box_img.src = box_img.src.replace("-rr", "");

// Since the user is probably still hovering over the box, make the menu disappear. It will reappear when they mouse over or click again.
document.getElementById('box_<%= @box.id %>_menu').style.display = 'none';

// reconfigure menu items on mouse-over menu for this box
var return_link_element = document.getElementById('box_<%= @box.id %>_return_link');
return_link_element.innerHTML = 'return this box';
return_link_element.href = '/boxes/<%=@box.id%>/request_box_return';

var container = document.getElementById("box_<%=@box.id%>_menu_list");
var checkout_element = document.getElementById("box_<%=@box.id%>_checkout")
container.removeChild(checkout_element)

<% if @box.inventorying_status == Box::NO_INVENTORYING_REQUESTED %>
	var container = document.getElementById("box_<%=@box.id%>_menu_list");
	var new_element = document.createElement('li');
	new_element.innerHTML = '<%= render :partial => "inv_req_link", :locals => { :box => @box } %>';
	new_element.id = 'box_<%= @box.id %>_inv_req';
	container.insertBefore(new_element, container.lastChild);
<% end %>

// refresh the cart image at the top of the screen
<% if !current_user.cart.nil? && !current_user.cart.empty? %>
	var cart_display = document.getElementById("cart-display");
	cart_display.innerHTML = '<p><a href="/account/cart">service requests in cart: <%= current_user.cart.num_items %></a></p>';
	cart_display.style.display = 'block';
<% else %>
	var cart_display = document.getElementById("cart-display");
	cart_display.style.display = 'none';
<% end %>

app/views/boxes/edit.html.erb
<% @menu_page = :box %>
<%= render 'account/account_nav', :locals => { :menu_page => @menu_page } %>
<div id="internal-right">
<div class="simple_header">Editing box <%= @box.id %></div>
<%= render 'form' %>
</div>
<div class="clearer"></div>

app/views/boxes/index.html.erb
<% @menu_page = :boxes %>
<%= render 'account/account_nav', :locals => { :menu_page => @menu_page } %>
<div id="internal-right">
        <p class="browse-headline bottom-border">You currently have <strong><%= @boxes.size %></strong> active boxes. <a href="/account/store_more_boxes">Click here to add more.</a> 
	<% if @boxes.size > 0 %>
		Mouse over a box for options.
	<% end %></p>
	<% @boxes.each_with_index do |box, index| %>
		<% if index % 3 == 0 && index != 0 %>
	    <!-- DIVIDER -->
	    <div class="clearer bottom-border"></div>
	    <!-- END DIVIDER -->		
		<% end %>

        <!-- BROWSE BOX -->
        <div class="browse-box">
            <p class="browse-box-name">Box <%= box.box_num %></p>
            <p>
			<% if box.description %>
				<div style="width: 155; height: 1.3em; overflow: hidden"><%= box.description %></div>
			<% else %>
				<i>no description</i>
			<% end %>
			</p>
			<% if box.status == Box::NEW_STATUS && box.box_type == Box::VC_BOX_TYPE %>
				<% image_file = "status-inventory-to-you" %>
				<% alt = "In Transit" %>
			<% elsif box.status == Box::IN_TRANSIT_TO_YOU_STATUS %>
				<% image_file = "status-inventory-to-you" %>
				<% alt = "In Transit" %>
			<% elsif box.status == Box::RETURN_REQUESTED_STATUS %>
				<% image_file = "status-inventory-to-you" %>
				<% alt = "In Transit" %>	
			<% elsif box.status == Box::RETURNED_STATUS %>
				<% image_file = "returned_box" %>
				<% alt = "Returned" %>
			<% elsif box.status == Box::IN_TRANSIT_TO_TVC_STATUS %>
				<% image_file = "status-inventory-to-us" %>
				<% alt = "In Transit" %>			
			<% elsif box.status == Box::IN_STORAGE_STATUS && (box.inventorying_status == Box::NO_INVENTORYING_REQUESTED || box.inventorying_status.nil?) %>
				<% image_file = "status-inventory-storage" %>
				<% alt = "In Storage" %>
			<% elsif box.status == Box::IN_STORAGE_STATUS && box.inventorying_status == Box::INVENTORYING_REQUESTED %>
				<% image_file = "status-inventory-processing" %>
				<% alt = "Inventory Being Processed" %>
			<% elsif box.status == Box::IN_STORAGE_STATUS && box.inventorying_status == Box::INVENTORIED %>
				<% image_file = "status-inventory-complete" %>
				<% alt = "Inventory Complete" %>
			<% elsif box.status == Box::BEING_PREPARED_STATUS %>
				<% image_file = "status-inventory-packed" %>
				<% alt = "Being Prepared by You" %>
			<% end %>
			
			<% if !current_user.cart.nil? && current_user.cart.contains_return_request_for(box) %>
				<% image_file += "-rr" %>
			<% end %>
			
            <img src="/images/<%= image_file %>.jpg" alt="<%= alt %>" id="box_img_<%=box.id%>"/>
            <p><strong>Status: </strong><%= box.status_en %></p>
            <p><strong>Number of Items: </strong>
			<% if box.inventorying_status == Box::INVENTORIED %>
				<%= box.item_count %></p>
			<% else %>
				Unknown
			<% end %>
			<% if box.status == Box::IN_STORAGE_STATUS %>
			<p><strong>Date Received: </strong><%=box.received_at.blank? ? "unknown" : box.received_at.strftime('%m/%d/%Y')%></p>
			<% elsif box.received_at.nil? %>
				<p><strong>Date Ordered: </strong><%=box.created_at.strftime('%m/%d/%Y')%></p>
			<% else %>
				<p><strong>Return Requested: </strong><%= box.return_requested_at.strftime('%m/%d/%Y')%></p>
			<% end %>
            <div class="browse-box-menu">
                <div class="browse-box-menu-contents" id="box_<%=box.id%>_menu">
                    <p class="browse-box-menu-contents-head">Box Options</p>
                    <ul id="box_<%= box.id %>_menu_list">
                        <li><a href="/boxes/<%= box.id %>/edit">edit description</a></li>
						<% if box.status == Box::IN_STORAGE_STATUS && (current_user.cart.nil? || !current_user.cart.contains_return_request_for(box)) %>
                        	<li><%= link_to "return this box", "/boxes/#{box.id}/request_box_return", :remote => true, :id => "box_#{box.id}_return_link" %></li>
						<% elsif !current_user.cart.nil? && current_user.cart.contains_return_request_for(box) %>
							<li><%= link_to "cancel return request", "/boxes/#{box.id}/cancel_box_return_request", :remote => true, :id => "box_#{box.id}_return_link" %></li>
							<li id="box_<%= box.id %>_checkout"><a href="/account/check_out">proceed to checkout</a></li>
						<% end %>
						<% if box.status == Box::IN_STORAGE_STATUS && box.inventorying_status == Box::NO_INVENTORYING_REQUESTED %>
							<li id="box_<%= box.id %>_inv_req">
								<%= render :partial => "inv_req_link", :locals => { :box => box } %>
							</li>
						<% end %>
						<% if box.inventorying_status == Box::INVENTORIED %>
                        <li><a href="/boxes/<%= box.id %>/stored_items">view inventory</a></li>
						<% end %>
						<% if box.box_type == Box::CUST_BOX_TYPE && box.status == Box::BEING_PREPARED_STATUS %>
							<li>
								<% if !current_user.gets_labels_emailed? %>
									<a href="/box/<%=box.id%>/get_label" onclick="alert('This will download a PDF of a FedEx label for you to print. Call 1-800-GO-FEDEX to have FedEx pick up your package. Be sure to mark the \'inventorying\' checkbox on the label if you would like us to inventory your box!')">shipping label</a>
								<% else %>
									<% if box.last_shipment_to_tvc && box.last_shipment_to_tvc.last_label_emailed %>
										<%= link_to "shipping label", "/boxes/#{box.id}/email_shipping_label", :remote => true, :id => "box_#{box.id}_label_link", :confirm => "This box's label was emailed to you on #{box.last_shipment_to_tvc.last_label_emailed.strftime '%m/%d/%Y'}; click ok to cancel this label and issue another one, or cancel to do nothing." %>
									<% else %>
										<%= link_to "shipping label", "/boxes/#{box.id}/email_shipping_label", :remote => true, :id => "box_#{box.id}_label_link" %>
									<% end %>
								<% end %>
								</li>
						<% end %>                        
                    </ul>
                </div>
            </div>
        </div>
        <!-- END BROWSE BOX -->
		
	<% end %>        
    </div>
<div class="clearer"></div>
<div style="display: none">
	<a href="#first_box_return_div" id="first_box_return_link"></a>
	<div id="first_box_return_div" style="width: 500px; border: 1px solid black; padding: 5px 5px 5px 5px; text-align: center">
		You have selected to return a box to you. No problem! You can choose to select more boxes to return, or you can proceed to checkout immediately to see the total estimated shipping cost and indicate where we should ship your box(es).
		<br><br>
		If you choose to select more boxes to return, simply click the "cart" box at the top of the screen to proceed to checkout.
		<br><br>
		What would you like to do?<br><br>
		<%= form_tag "/account/check_out", :class => "standard", :method => "get" do  %>
			<input type="submit" class="button" value="Return More Boxes" onclick="$.fancybox.close(); return false;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
			<input type="submit" class="button" value="Go to Checkout">
		<% end %>
	</div>
</div>

app/views/boxes/new.html.erb
<h1>New box</h1>

<%= render 'form' %>

<%= link_to 'Back', boxes_path %>

app/views/boxes/receive_box.html.erb
<% @admin_page = :receiving %>
<%= render :partial => "admin/admin_menu", :locals => { :admin_page => @admin_page } %>
<div id="internal-right">
	<div class="login-slim-centered">
	<div class="simple_header">Box Receiving</div>
		<% if @messages.size > 0 %>
			<ul>
				<% @messages.each do |message| %>
					<li><%= message %></li>
				<% end %>
			</ul>
		<% end %>
		
		<% if @error_messages.size > 0 %>
			<div class="error_label">
				<ul>
					<% @error_messages.each do |error_message| %>
						<li><%= error_message %></li>
					<% end %>
				</ul>
			</div>
		<% end %>		
		<br><br><br>
		<%= form_tag "", :class => "standard", :id => "box_form", :onsubmit => "cf_submit.disabled=true;" do %>
			<div class="field clearfix">
				Box ID:
				<%= text_field_tag :box_id, "", :class => "textbox", :value => params[:box_id] %>
			</div>
			<div class="field clearfix">
				Box dimensions (w/l/h) in INCHES:
				<%= text_field_tag :width, "", :class => "textbox", :style => "width: 6", :placeholder => "width", :value => params[:width] %>
				<%= text_field_tag :length, "", :class => "textbox", :style => "width: 6", :placeholder => "length", :value => params[:length] %>
				<%= text_field_tag :height, "", :class => "textbox", :style => "width: 6", :placeholder => "height", :value => params[:height] %> 
			</div>
			<div class="field clearfix">
				Box weight in lbs:
				<%= text_field_tag :weight, "", :class => "textbox", :style => "width: 6", :placeholder => "weight", :value => params[:weight] %>&nbsp;
			</div>
			<div class="field clearfix">
				Box storage location:
				<%= text_field_tag :location, "", :class => "textbox", :style => "width: 6", :placeholder => "location", :value => params[:location] %>&nbsp;
			</div>
			<div class="field clearfix">
				Box marked for inventorying:
				<%= check_box_tag :marked_for_inventorying, "1", !params[:marked_for_inventorying].nil? %>
			</div>
			<div class="field clearfix">
				<%= submit_tag :submit, :class => "button", :id => "cf_submit", :onclick => "return formMonitor();" %>
			</div>
		<% end %>		
<script type="text/javascript" language="JavaScript">
document.forms['box_form'].elements['box_id'].focus();
</script>
</div>
</div>
<div class="clearer"></div>

app/views/boxes/request_box_return.js.erb
<% first_box = (current_user.cart.nil? ? true : (current_user.cart.num_box_return_requests == 1)) %>
// Change the clicked box image
var box_img = document.getElementById('box_img_<%= @box.id %>')
<% if @box.status == Box::IN_STORAGE_STATUS && @box.inventorying_status == Box::NO_INVENTORYING_REQUESTED %>
	box_img.src = '/images/status-inventory-storage-rr.jpg';
<% elsif @box.status == Box::IN_STORAGE_STATUS && @box.inventorying_status == Box::INVENTORYING_REQUESTED %>
	box_img.src = '/images/status-inventory-processing-rr.jpg';
<% elsif @box.status == Box::IN_STORAGE_STATUS && @box.inventorying_status == Box::INVENTORIED %>
	box_img.src = '/images/status-inventory-complete-rr.jpg';
<% end %>
// Since the user is probably still hovering over the box, make the menu disappear. It will reappear when they mouse over or click again.
document.getElementById('box_<%= @box.id %>_menu').style.display = 'none';

// reconfigure menu items on mouse-over menu for this box
var return_link_element = document.getElementById('box_<%= @box.id %>_return_link');
return_link_element.innerHTML = 'cancel return request';
return_link_element.href = '/boxes/<%=@box.id%>/cancel_box_return_request';

var container = document.getElementById("box_<%=@box.id%>_menu_list");
var new_element = document.createElement('li');
new_element.innerHTML = '<a href="/account/check_out">proceed to checkout</a>';
new_element.id = 'box_<%=@box.id%>_checkout';
container.insertBefore(new_element, container.lastChild);

<% if @box.inventorying_status == Box::NO_INVENTORYING_REQUESTED %>
	var inv_req_element = document.getElementById("box_<%=@box.id%>_inv_req")
	container.removeChild(inv_req_element)
<% end %>

// refresh the cart image at the top of the screen
<% if !current_user.cart.nil? && !current_user.cart.empty? %>
	var cart_display = document.getElementById("cart-display");
	cart_display.innerHTML = '<p><a href="/account/cart">service requests in cart: <%= current_user.cart.num_items %></a></p>';
	cart_display.style.display = 'block';
<% end %>

<% if first_box && current_user.boxes_in_storage.count > 1 %> 
	$("#first_box_return_link").trigger('click');
<% end %>

app/views/boxes/request_inventory.js.erb
// Change the clicked box image
var box_img = document.getElementById('box_img_<%= @box.id %>')
box_img.src = '/images/status-inventory-processing.jpg';

// reconfigure menu items on mouse-over menu for this box
var container = document.getElementById("box_<%=@box.id%>_menu_list");
var inv_element = document.getElementById("box_<%=@box.id%>_inv_req")
container.removeChild(inv_element)

app/views/boxes/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_box_path(@box) %> |
<%= link_to 'Back', boxes_path %>

app/views/boxes/user_add_tag.js.erb
document.getElementById("tags_container").innerHTML = '<%= escape_javascript render(:partial => "user_stored_item_tags", :locals => {:stored_item => @stored_item}) %>';
document.forms['tags_form'].elements['tag'].value = "";

app/views/boxes/user_delete_tag.js.erb
document.getElementById("tags_container").innerHTML = '<%= escape_javascript render(:partial => "user_stored_item_tags", :locals => {:stored_item => @stored_item}) %>';